// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: otp/otp_service.proto

package otpconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	otp "shopify-user-command-module/contract/protogen/otp"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OTPCommandServiceName is the fully-qualified name of the OTPCommandService service.
	OTPCommandServiceName = "otp.v1.OTPCommandService"
	// OTPQueryServiceName is the fully-qualified name of the OTPQueryService service.
	OTPQueryServiceName = "otp.v1.OTPQueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OTPCommandServiceVerifyProcedure is the fully-qualified name of the OTPCommandService's Verify
	// RPC.
	OTPCommandServiceVerifyProcedure = "/otp.v1.OTPCommandService/Verify"
	// OTPCommandServiceResendProcedure is the fully-qualified name of the OTPCommandService's Resend
	// RPC.
	OTPCommandServiceResendProcedure = "/otp.v1.OTPCommandService/Resend"
)

// OTPCommandServiceClient is a client for the otp.v1.OTPCommandService service.
type OTPCommandServiceClient interface {
	// Verify otp in the system.
	Verify(context.Context, *connect.Request[otp.VerifyRequest]) (*connect.Response[otp.VerifyResponse], error)
	// Resend otp in the system
	Resend(context.Context, *connect.Request[otp.ResendRequest]) (*connect.Response[otp.ResendResponse], error)
}

// NewOTPCommandServiceClient constructs a client for the otp.v1.OTPCommandService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOTPCommandServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OTPCommandServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	oTPCommandServiceMethods := otp.File_otp_otp_service_proto.Services().ByName("OTPCommandService").Methods()
	return &oTPCommandServiceClient{
		verify: connect.NewClient[otp.VerifyRequest, otp.VerifyResponse](
			httpClient,
			baseURL+OTPCommandServiceVerifyProcedure,
			connect.WithSchema(oTPCommandServiceMethods.ByName("Verify")),
			connect.WithClientOptions(opts...),
		),
		resend: connect.NewClient[otp.ResendRequest, otp.ResendResponse](
			httpClient,
			baseURL+OTPCommandServiceResendProcedure,
			connect.WithSchema(oTPCommandServiceMethods.ByName("Resend")),
			connect.WithClientOptions(opts...),
		),
	}
}

// oTPCommandServiceClient implements OTPCommandServiceClient.
type oTPCommandServiceClient struct {
	verify *connect.Client[otp.VerifyRequest, otp.VerifyResponse]
	resend *connect.Client[otp.ResendRequest, otp.ResendResponse]
}

// Verify calls otp.v1.OTPCommandService.Verify.
func (c *oTPCommandServiceClient) Verify(ctx context.Context, req *connect.Request[otp.VerifyRequest]) (*connect.Response[otp.VerifyResponse], error) {
	return c.verify.CallUnary(ctx, req)
}

// Resend calls otp.v1.OTPCommandService.Resend.
func (c *oTPCommandServiceClient) Resend(ctx context.Context, req *connect.Request[otp.ResendRequest]) (*connect.Response[otp.ResendResponse], error) {
	return c.resend.CallUnary(ctx, req)
}

// OTPCommandServiceHandler is an implementation of the otp.v1.OTPCommandService service.
type OTPCommandServiceHandler interface {
	// Verify otp in the system.
	Verify(context.Context, *connect.Request[otp.VerifyRequest]) (*connect.Response[otp.VerifyResponse], error)
	// Resend otp in the system
	Resend(context.Context, *connect.Request[otp.ResendRequest]) (*connect.Response[otp.ResendResponse], error)
}

// NewOTPCommandServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOTPCommandServiceHandler(svc OTPCommandServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	oTPCommandServiceMethods := otp.File_otp_otp_service_proto.Services().ByName("OTPCommandService").Methods()
	oTPCommandServiceVerifyHandler := connect.NewUnaryHandler(
		OTPCommandServiceVerifyProcedure,
		svc.Verify,
		connect.WithSchema(oTPCommandServiceMethods.ByName("Verify")),
		connect.WithHandlerOptions(opts...),
	)
	oTPCommandServiceResendHandler := connect.NewUnaryHandler(
		OTPCommandServiceResendProcedure,
		svc.Resend,
		connect.WithSchema(oTPCommandServiceMethods.ByName("Resend")),
		connect.WithHandlerOptions(opts...),
	)
	return "/otp.v1.OTPCommandService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OTPCommandServiceVerifyProcedure:
			oTPCommandServiceVerifyHandler.ServeHTTP(w, r)
		case OTPCommandServiceResendProcedure:
			oTPCommandServiceResendHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOTPCommandServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOTPCommandServiceHandler struct{}

func (UnimplementedOTPCommandServiceHandler) Verify(context.Context, *connect.Request[otp.VerifyRequest]) (*connect.Response[otp.VerifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otp.v1.OTPCommandService.Verify is not implemented"))
}

func (UnimplementedOTPCommandServiceHandler) Resend(context.Context, *connect.Request[otp.ResendRequest]) (*connect.Response[otp.ResendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("otp.v1.OTPCommandService.Resend is not implemented"))
}

// OTPQueryServiceClient is a client for the otp.v1.OTPQueryService service.
type OTPQueryServiceClient interface {
}

// NewOTPQueryServiceClient constructs a client for the otp.v1.OTPQueryService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOTPQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OTPQueryServiceClient {
	return &oTPQueryServiceClient{}
}

// oTPQueryServiceClient implements OTPQueryServiceClient.
type oTPQueryServiceClient struct {
}

// OTPQueryServiceHandler is an implementation of the otp.v1.OTPQueryService service.
type OTPQueryServiceHandler interface {
}

// NewOTPQueryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOTPQueryServiceHandler(svc OTPQueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	return "/otp.v1.OTPQueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOTPQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOTPQueryServiceHandler struct{}
