// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/user_service.proto

package userconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	user "shopify-user-command-module/contract/protogen/user"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserCommandServiceName is the fully-qualified name of the UserCommandService service.
	UserCommandServiceName = "user.v1.UserCommandService"
	// UserQueryServiceName is the fully-qualified name of the UserQueryService service.
	UserQueryServiceName = "user.v1.UserQueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserCommandServiceRegisterProcedure is the fully-qualified name of the UserCommandService's
	// Register RPC.
	UserCommandServiceRegisterProcedure = "/user.v1.UserCommandService/Register"
	// UserCommandServiceLoginProcedure is the fully-qualified name of the UserCommandService's Login
	// RPC.
	UserCommandServiceLoginProcedure = "/user.v1.UserCommandService/Login"
)

// UserCommandServiceClient is a client for the user.v1.UserCommandService service.
type UserCommandServiceClient interface {
	// registers user.
	Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.RegisterResponse], error)
	// login user.
	Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.LoginResponse], error)
}

// NewUserCommandServiceClient constructs a client for the user.v1.UserCommandService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserCommandServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserCommandServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userCommandServiceMethods := user.File_user_user_service_proto.Services().ByName("UserCommandService").Methods()
	return &userCommandServiceClient{
		register: connect.NewClient[user.RegisterRequest, user.RegisterResponse](
			httpClient,
			baseURL+UserCommandServiceRegisterProcedure,
			connect.WithSchema(userCommandServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[user.LoginRequest, user.LoginResponse](
			httpClient,
			baseURL+UserCommandServiceLoginProcedure,
			connect.WithSchema(userCommandServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userCommandServiceClient implements UserCommandServiceClient.
type userCommandServiceClient struct {
	register *connect.Client[user.RegisterRequest, user.RegisterResponse]
	login    *connect.Client[user.LoginRequest, user.LoginResponse]
}

// Register calls user.v1.UserCommandService.Register.
func (c *userCommandServiceClient) Register(ctx context.Context, req *connect.Request[user.RegisterRequest]) (*connect.Response[user.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls user.v1.UserCommandService.Login.
func (c *userCommandServiceClient) Login(ctx context.Context, req *connect.Request[user.LoginRequest]) (*connect.Response[user.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// UserCommandServiceHandler is an implementation of the user.v1.UserCommandService service.
type UserCommandServiceHandler interface {
	// registers user.
	Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.RegisterResponse], error)
	// login user.
	Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.LoginResponse], error)
}

// NewUserCommandServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserCommandServiceHandler(svc UserCommandServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userCommandServiceMethods := user.File_user_user_service_proto.Services().ByName("UserCommandService").Methods()
	userCommandServiceRegisterHandler := connect.NewUnaryHandler(
		UserCommandServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(userCommandServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	userCommandServiceLoginHandler := connect.NewUnaryHandler(
		UserCommandServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(userCommandServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.v1.UserCommandService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserCommandServiceRegisterProcedure:
			userCommandServiceRegisterHandler.ServeHTTP(w, r)
		case UserCommandServiceLoginProcedure:
			userCommandServiceLoginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserCommandServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserCommandServiceHandler struct{}

func (UnimplementedUserCommandServiceHandler) Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserCommandService.Register is not implemented"))
}

func (UnimplementedUserCommandServiceHandler) Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserCommandService.Login is not implemented"))
}

// UserQueryServiceClient is a client for the user.v1.UserQueryService service.
type UserQueryServiceClient interface {
}

// NewUserQueryServiceClient constructs a client for the user.v1.UserQueryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserQueryServiceClient {
	return &userQueryServiceClient{}
}

// userQueryServiceClient implements UserQueryServiceClient.
type userQueryServiceClient struct {
}

// UserQueryServiceHandler is an implementation of the user.v1.UserQueryService service.
type UserQueryServiceHandler interface {
}

// NewUserQueryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserQueryServiceHandler(svc UserQueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	return "/user.v1.UserQueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserQueryServiceHandler struct{}
