// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: otp/otp.proto

package otp

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_otp_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *VerifyRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_otp_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyResponse) GetAccessExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessExpiresAt
	}
	return nil
}

func (x *VerifyResponse) GetRefreshExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return nil
}

type ResendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendRequest) Reset() {
	*x = ResendRequest{}
	mi := &file_otp_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendRequest) ProtoMessage() {}

func (x *ResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendRequest.ProtoReflect.Descriptor instead.
func (*ResendRequest) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{2}
}

func (x *ResendRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ResendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendResponse) Reset() {
	*x = ResendResponse{}
	mi := &file_otp_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendResponse) ProtoMessage() {}

func (x *ResendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendResponse.ProtoReflect.Descriptor instead.
func (*ResendResponse) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{3}
}

func (x *ResendResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_otp_otp_proto protoreflect.FileDescriptor

const file_otp_otp_proto_rawDesc = "" +
	"\n" +
	"\rotp/otp.proto\x12\x06otp.v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\rVerifyRequest\x12,\n" +
	"\rsession_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fsessionToken\x12%\n" +
	"\x03otp\x18\x02 \x01(\tB\x13\xfaB\x10r\x0e\x10\x06\x18\x062\b^[0-9]+$R\x03otp\"\xea\x01\n" +
	"\x0eVerifyResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12F\n" +
	"\x11access_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0faccessExpiresAt\x12H\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10refreshExpiresAt\"=\n" +
	"\rResendRequest\x12,\n" +
	"\rsession_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fsessionToken\"K\n" +
	"\x0eResendResponse\x129\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB3Z1shopify-user-command-module/contract/protogen/otpb\x06proto3"

var (
	file_otp_otp_proto_rawDescOnce sync.Once
	file_otp_otp_proto_rawDescData []byte
)

func file_otp_otp_proto_rawDescGZIP() []byte {
	file_otp_otp_proto_rawDescOnce.Do(func() {
		file_otp_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otp_otp_proto_rawDesc), len(file_otp_otp_proto_rawDesc)))
	})
	return file_otp_otp_proto_rawDescData
}

var file_otp_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_otp_otp_proto_goTypes = []any{
	(*VerifyRequest)(nil),         // 0: otp.v1.VerifyRequest
	(*VerifyResponse)(nil),        // 1: otp.v1.VerifyResponse
	(*ResendRequest)(nil),         // 2: otp.v1.ResendRequest
	(*ResendResponse)(nil),        // 3: otp.v1.ResendResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_otp_otp_proto_depIdxs = []int32{
	4, // 0: otp.v1.VerifyResponse.access_expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: otp.v1.VerifyResponse.refresh_expires_at:type_name -> google.protobuf.Timestamp
	4, // 2: otp.v1.ResendResponse.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_otp_otp_proto_init() }
func file_otp_otp_proto_init() {
	if File_otp_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otp_otp_proto_rawDesc), len(file_otp_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otp_otp_proto_goTypes,
		DependencyIndexes: file_otp_otp_proto_depIdxs,
		MessageInfos:      file_otp_otp_proto_msgTypes,
	}.Build()
	File_otp_otp_proto = out.File
	file_otp_otp_proto_goTypes = nil
	file_otp_otp_proto_depIdxs = nil
}
