// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: otp/otp_service.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_otp_otp_service_proto protoreflect.FileDescriptor

const file_otp_otp_service_proto_rawDesc = "" +
	"\n" +
	"\x15otp/otp_service.proto\x12\x06otp.v1\x1a\rotp/otp.proto2\x85\x01\n" +
	"\x11OTPCommandService\x127\n" +
	"\x06Verify\x12\x15.otp.v1.VerifyRequest\x1a\x16.otp.v1.VerifyResponse\x127\n" +
	"\x06Resend\x12\x15.otp.v1.ResendRequest\x1a\x16.otp.v1.ResendResponse2\x11\n" +
	"\x0fOTPQueryServiceB3Z1shopify-user-command-module/contract/protogen/otpb\x06proto3"

var file_otp_otp_service_proto_goTypes = []any{
	(*VerifyRequest)(nil),  // 0: otp.v1.VerifyRequest
	(*ResendRequest)(nil),  // 1: otp.v1.ResendRequest
	(*VerifyResponse)(nil), // 2: otp.v1.VerifyResponse
	(*ResendResponse)(nil), // 3: otp.v1.ResendResponse
}
var file_otp_otp_service_proto_depIdxs = []int32{
	0, // 0: otp.v1.OTPCommandService.Verify:input_type -> otp.v1.VerifyRequest
	1, // 1: otp.v1.OTPCommandService.Resend:input_type -> otp.v1.ResendRequest
	2, // 2: otp.v1.OTPCommandService.Verify:output_type -> otp.v1.VerifyResponse
	3, // 3: otp.v1.OTPCommandService.Resend:output_type -> otp.v1.ResendResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_otp_otp_service_proto_init() }
func file_otp_otp_service_proto_init() {
	if File_otp_otp_service_proto != nil {
		return
	}
	file_otp_otp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otp_otp_service_proto_rawDesc), len(file_otp_otp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_otp_otp_service_proto_goTypes,
		DependencyIndexes: file_otp_otp_service_proto_depIdxs,
	}.Build()
	File_otp_otp_service_proto = out.File
	file_otp_otp_service_proto_goTypes = nil
	file_otp_otp_service_proto_depIdxs = nil
}
