// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT user_id, password_hash, password_version, password_updated_at
FROM credentials
WHERE user_id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, userID pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, userID)
	var i Credential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (
    user_id,
    password_hash,
    password_version,
    password_updated_at
)
VALUES ($1, $2, $3, $4)
`

type InsertCredentialParams struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordVersion   int32
	PasswordUpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.UserID,
		arg.PasswordHash,
		arg.PasswordVersion,
		arg.PasswordUpdatedAt,
	)
	return err
}
