// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoginStatsByID = `-- name: GetLoginStatsByID :one
SELECT user_id, failed_count, lock_until, last_failed_at, updated_at
FROM login_stats
WHERE user_id = $1
`

func (q *Queries) GetLoginStatsByID(ctx context.Context, userID pgtype.UUID) (LoginStat, error) {
	row := q.db.QueryRow(ctx, getLoginStatsByID, userID)
	var i LoginStat
	err := row.Scan(
		&i.UserID,
		&i.FailedCount,
		&i.LockUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveLoginStats = `-- name: SaveLoginStats :exec
INSERT INTO login_stats (
    user_id,
    failed_count,
    lock_until,
    last_failed_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    failed_count = EXCLUDED.failed_count,
    lock_until = EXCLUDED.lock_until,
    last_failed_at = EXCLUDED.last_failed_at,
    updated_at = EXCLUDED.updated_at
`

type SaveLoginStatsParams struct {
	UserID       pgtype.UUID
	FailedCount  int32
	LockUntil    pgtype.Timestamptz
	LastFailedAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SaveLoginStats(ctx context.Context, arg SaveLoginStatsParams) error {
	_, err := q.db.Exec(ctx, saveLoginStats,
		arg.UserID,
		arg.FailedCount,
		arg.LockUntil,
		arg.LastFailedAt,
		arg.UpdatedAt,
	)
	return err
}
