// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLoginAttemptsByID = `-- name: FindLoginAttemptsByID :one
SELECT user_id, failed_count, lock_until, last_failed_at, updated_at
FROM login_attempts
WHERE user_id = $1
`

func (q *Queries) FindLoginAttemptsByID(ctx context.Context, userID pgtype.UUID) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, findLoginAttemptsByID, userID)
	var i LoginAttempt
	err := row.Scan(
		&i.UserID,
		&i.FailedCount,
		&i.LockUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveLoginAttempt = `-- name: SaveLoginAttempt :exec
INSERT INTO login_attempts (
    user_id,
    failed_count,
    lock_until,
    last_failed_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    failed_count = EXCLUDED.failed_count,
    lock_until = EXCLUDED.lock_until,
    last_failed_at = EXCLUDED.last_failed_at,
    updated_at = EXCLUDED.updated_at
`

type SaveLoginAttemptParams struct {
	UserID       pgtype.UUID
	FailedCount  int32
	LockUntil    pgtype.Timestamptz
	LastFailedAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SaveLoginAttempt(ctx context.Context, arg SaveLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, saveLoginAttempt,
		arg.UserID,
		arg.FailedCount,
		arg.LockUntil,
		arg.LastFailedAt,
		arg.UpdatedAt,
	)
	return err
}
