// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoginAttempt struct {
	UserID       pgtype.UUID
	FailedCount  int32
	LockUntil    pgtype.Timestamptz
	LastFailedAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Status          string
	Roles           []string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type UserAddress struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CountryID    string
	CountryName  string
	ProvinceID   string
	ProvinceName string
	WardID       string
	WardName     string
	AddressLine  string
	ReceiverName string
	PhoneNumber  string
	Label        string
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserCredential struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordVersion   int32
	PasswordUpdatedAt pgtype.Timestamptz
}

type UserProfile struct {
	UserID      pgtype.UUID
	FullName    string
	Gender      string
	PhoneNumber pgtype.Text
	AvatarUrl   pgtype.Text
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
