// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Label        string
	ReceiverName string
	PhoneNumber  string
	AddressLine  string
	Ward         string
	District     string
	City         string
	Country      string
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Credential struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordVersion   int32
	PasswordUpdatedAt pgtype.Timestamptz
}

type LoginStat struct {
	UserID            pgtype.UUID
	LastLoginAt       pgtype.Timestamptz
	FailedLoginCount  int32
	LastFailedLoginAt pgtype.Timestamptz
	LockUntil         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	Status         string
	ProcessedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey pgtype.UUID
	RetryCount     int32
	NextRetryAt    pgtype.Timestamptz
	ErrorMessage   pgtype.Text
}

type Profile struct {
	UserID      pgtype.UUID
	FullName    string
	Gender      string
	PhoneNumber pgtype.Text
	AvatarUrl   pgtype.Text
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Shop struct {
	ID          pgtype.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	LogoUrl     pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShopMember struct {
	ShopID pgtype.UUID
	UserID pgtype.UUID
	RoleID int32
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Status          string
	Roles           []string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}
