// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveOutbox = `-- name: SaveOutbox :exec
INSERT INTO outbox (
    id,
    aggregate_id,
    aggregate_type,
    event_type,
    payload,
    partition_key,
    idempotency_key,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveOutboxParams struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) SaveOutbox(ctx context.Context, arg SaveOutboxParams) error {
	_, err := q.db.Exec(ctx, saveOutbox,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.PartitionKey,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	return err
}

const saveOutboxBatch = `-- name: SaveOutboxBatch :exec
INSERT INTO outbox (
    id,
    aggregate_id,
    aggregate_type,
    event_type,
    payload,
    partition_key,
    idempotency_key,
    created_at
)
SELECT 
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::jsonb[]),
    unnest($6::text[]),
    unnest($7::uuid[]),
    unnest($8::timestamptz[])
`

type SaveOutboxBatchParams struct {
	Ids             []pgtype.UUID
	AggregateIds    []pgtype.UUID
	AggregateTypes  []string
	EventTypes      []string
	Payloads        [][]byte
	PartitionKeys   []string
	IdempotencyKeys []pgtype.UUID
	CreatedAts      []pgtype.Timestamptz
}

func (q *Queries) SaveOutboxBatch(ctx context.Context, arg SaveOutboxBatchParams) error {
	_, err := q.db.Exec(ctx, saveOutboxBatch,
		arg.Ids,
		arg.AggregateIds,
		arg.AggregateTypes,
		arg.EventTypes,
		arg.Payloads,
		arg.PartitionKeys,
		arg.IdempotencyKeys,
		arg.CreatedAts,
	)
	return err
}
