// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shops.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBySlug = `-- name: CountBySlug :one
SELECT 
    1
FROM shops 
WHERE slug = $1
`

func (q *Queries) CountBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, countBySlug, slug)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, owner_id, name, slug, status, created_by, updated_by, created_at, updated_at, deleted_at
FROM shops
WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id pgtype.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const saveShop = `-- name: SaveShop :exec
INSERT INTO shops (
    id,
    owner_id,
    name,
    slug,
    status,
    created_by,
    updated_by,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SaveShopParams struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Slug      string
	Status    string
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SaveShop(ctx context.Context, arg SaveShopParams) error {
	_, err := q.db.Exec(ctx, saveShop,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateShopStatus = `-- name: UpdateShopStatus :exec
UPDATE shops
SET
    status = $2,
    updated_by = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateShopStatusParams struct {
	ID        pgtype.UUID
	Status    string
	UpdatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateShopStatus(ctx context.Context, arg UpdateShopStatusParams) error {
	_, err := q.db.Exec(ctx, updateShopStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
