// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShopProfileByID = `-- name: GetShopProfileByID :one
SELECT shop_id, description, logo_url, banner_url, created_by, updated_by, created_at, updated_at
FROM shop_profiles
WHERE shop_id = $1
`

func (q *Queries) GetShopProfileByID(ctx context.Context, shopID pgtype.UUID) (ShopProfile, error) {
	row := q.db.QueryRow(ctx, getShopProfileByID, shopID)
	var i ShopProfile
	err := row.Scan(
		&i.ShopID,
		&i.Description,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveShopProfile = `-- name: SaveShopProfile :exec
INSERT INTO shop_profiles (
    shop_id,
    description,
    logo_url,
    banner_url,
    created_by,
    updated_by,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveShopProfileParams struct {
	ShopID      pgtype.UUID
	Description pgtype.Text
	LogoUrl     pgtype.Text
	BannerUrl   pgtype.Text
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SaveShopProfile(ctx context.Context, arg SaveShopProfileParams) error {
	_, err := q.db.Exec(ctx, saveShopProfile,
		arg.ShopID,
		arg.Description,
		arg.LogoUrl,
		arg.BannerUrl,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
