// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_addresses.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRequiredAddresses = `-- name: CheckRequiredAddresses :one
SELECT 
    EXISTS (
        SELECT 1 
        FROM shop_addresses sa_pickup 
        WHERE sa_pickup.shop_id = $1 AND sa_pickup.type = 'PICKUP'
    ) AS has_pickup,
    EXISTS (
        SELECT 1 
        FROM shop_addresses sa_return 
        WHERE sa_return.shop_id = $1 AND sa_return.type = 'RETURN'
    ) AS has_return
`

type CheckRequiredAddressesRow struct {
	HasPickup bool
	HasReturn bool
}

func (q *Queries) CheckRequiredAddresses(ctx context.Context, shopID pgtype.UUID) (CheckRequiredAddressesRow, error) {
	row := q.db.QueryRow(ctx, checkRequiredAddresses, shopID)
	var i CheckRequiredAddressesRow
	err := row.Scan(&i.HasPickup, &i.HasReturn)
	return i, err
}

const saveShopAddress = `-- name: SaveShopAddress :exec
INSERT INTO shop_addresses (
    id,
    shop_id, 

    country_id,
    city_id,
    district_id, 
    ward_id,

    address_line,
    contact_name,
    phone_number,
    type,

    created_at,
    updated_at,

    created_by,
    updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type SaveShopAddressParams struct {
	ID          pgtype.UUID
	ShopID      pgtype.UUID
	CountryID   int32
	CityID      int32
	DistrictID  int32
	WardID      int32
	AddressLine string
	ContactName string
	PhoneNumber string
	Type        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
}

func (q *Queries) SaveShopAddress(ctx context.Context, arg SaveShopAddressParams) error {
	_, err := q.db.Exec(ctx, saveShopAddress,
		arg.ID,
		arg.ShopID,
		arg.CountryID,
		arg.CityID,
		arg.DistrictID,
		arg.WardID,
		arg.AddressLine,
		arg.ContactName,
		arg.PhoneNumber,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}
