// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_members_roles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addShopMembersBatch = `-- name: AddShopMembersBatch :exec
INSERT INTO shop_members (
    shop_id,
    member_id, 
    added_by,
    joined_at
) 
SELECT 
    $1,
    unnest($2::uuid[]),
    $3,
    $4
ON CONFLICT (shop_id, member_id) DO NOTHING
`

type AddShopMembersBatchParams struct {
	ShopID    pgtype.UUID
	MemberIds []pgtype.UUID
	AddedBy   pgtype.UUID
	JoinedAt  pgtype.Timestamptz
}

func (q *Queries) AddShopMembersBatch(ctx context.Context, arg AddShopMembersBatchParams) error {
	_, err := q.db.Exec(ctx, addShopMembersBatch,
		arg.ShopID,
		arg.MemberIds,
		arg.AddedBy,
		arg.JoinedAt,
	)
	return err
}

const assignShopMemberRolesBatch = `-- name: AssignShopMemberRolesBatch :exec
INSERT INTO shop_member_roles (
    shop_id,
    member_id,
    role_id,
    updated_by
)
SELECT 
    $1,
    unnest($2::uuid[]), 
    unnest($3::int[]),
    $4
ON CONFLICT (shop_id, member_id, role_id) DO UPDATE 
SET updated_by = EXCLUDED.updated_by
`

type AssignShopMemberRolesBatchParams struct {
	ShopID    pgtype.UUID
	MemberIds []pgtype.UUID
	RoleIds   []int32
	UpdatedBy pgtype.UUID
}

func (q *Queries) AssignShopMemberRolesBatch(ctx context.Context, arg AssignShopMemberRolesBatchParams) error {
	_, err := q.db.Exec(ctx, assignShopMemberRolesBatch,
		arg.ShopID,
		arg.MemberIds,
		arg.RoleIds,
		arg.UpdatedBy,
	)
	return err
}

const clearShopMemberRolesBatch = `-- name: ClearShopMemberRolesBatch :exec
DELETE FROM shop_member_roles 
WHERE shop_id = $1 
  AND member_id = ANY($2::uuid[])
`

type ClearShopMemberRolesBatchParams struct {
	ShopID    pgtype.UUID
	MemberIds []pgtype.UUID
}

func (q *Queries) ClearShopMemberRolesBatch(ctx context.Context, arg ClearShopMemberRolesBatchParams) error {
	_, err := q.db.Exec(ctx, clearShopMemberRolesBatch, arg.ShopID, arg.MemberIds)
	return err
}

const getUserRolesInShop = `-- name: GetUserRolesInShop :many
SELECT 
    s.id AS shop_id,
    smr.role_id
FROM shops s
LEFT JOIN shop_member_roles smr ON s.id = smr.shop_id AND smr.member_id = $2
WHERE s.id = $1
`

type GetUserRolesInShopParams struct {
	ID       pgtype.UUID
	MemberID pgtype.UUID
}

type GetUserRolesInShopRow struct {
	ShopID pgtype.UUID
	RoleID pgtype.Int4
}

func (q *Queries) GetUserRolesInShop(ctx context.Context, arg GetUserRolesInShopParams) ([]GetUserRolesInShopRow, error) {
	rows, err := q.db.Query(ctx, getUserRolesInShop, arg.ID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesInShopRow
	for rows.Next() {
		var i GetUserRolesInShopRow
		if err := rows.Scan(&i.ShopID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
