// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_addresses.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveUserAddress = `-- name: SaveUserAddress :exec
INSERT INTO user_addresses (
    id,
    user_id, 
    country_id, 
    city_id, 
    district_id, 
    ward_id, 
    address_line, 
    receiver_name, 
    phone_number, 
    label, 
    is_default,
    created_at, 
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type SaveUserAddressParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CountryID    int32
	CityID       int32
	DistrictID   int32
	WardID       int32
	AddressLine  string
	ReceiverName string
	PhoneNumber  string
	Label        string
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SaveUserAddress(ctx context.Context, arg SaveUserAddressParams) error {
	_, err := q.db.Exec(ctx, saveUserAddress,
		arg.ID,
		arg.UserID,
		arg.CountryID,
		arg.CityID,
		arg.DistrictID,
		arg.WardID,
		arg.AddressLine,
		arg.ReceiverName,
		arg.PhoneNumber,
		arg.Label,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
