// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_credentials.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserCredentialByID = `-- name: GetUserCredentialByID :one
SELECT user_id, password_hash, password_version, password_updated_at
FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) GetUserCredentialByID(ctx context.Context, userID pgtype.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByID, userID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const saveUserCredential = `-- name: SaveUserCredential :exec
INSERT INTO user_credentials (
    user_id,
    password_hash,
    password_version,
    password_updated_at
)
VALUES ($1, $2, $3, $4)
`

type SaveUserCredentialParams struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordVersion   int32
	PasswordUpdatedAt pgtype.Timestamptz
}

func (q *Queries) SaveUserCredential(ctx context.Context, arg SaveUserCredentialParams) error {
	_, err := q.db.Exec(ctx, saveUserCredential,
		arg.UserID,
		arg.PasswordHash,
		arg.PasswordVersion,
		arg.PasswordUpdatedAt,
	)
	return err
}
