// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    email_verified_at,
    status,
    roles,
    created_at,
    updated_at,
    deleted_at
)
VALUES (
    $1::uuid,
    $2::text,
    $3::timestamptz,
    $4::text,
    $5::text[],
    $6::timestamptz,
    $7::timestamptz,
    $8::timestamptz
)
`

type CreateUserParams struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Status          string
	Roles           []string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.Status,
		arg.Roles,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, email_verified_at, status, roles, created_at, updated_at, deleted_at 
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, email_verified_at, status, roles, created_at, updated_at, deleted_at 
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    email = $2,
    email_verified_at = $3,
    status = $4,
    roles = $5,
    updated_at = $6,
    deleted_at = $7
WHERE id = $1
`

type UpdateUserParams struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Status          string
	Roles           []string
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.Status,
		arg.Roles,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
