// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_credentials.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserCredential = `-- name: CreateUserCredential :exec
INSERT INTO user_credentials (
    user_id,
    password_hash,
    password_version,
    password_updated_at
)
VALUES ($1, $2, $3, $4)
`

type CreateUserCredentialParams struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordVersion   int32
	PasswordUpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) error {
	_, err := q.db.Exec(ctx, createUserCredential,
		arg.UserID,
		arg.PasswordHash,
		arg.PasswordVersion,
		arg.PasswordUpdatedAt,
	)
	return err
}

const findUserCredentialByID = `-- name: FindUserCredentialByID :one
SELECT user_id, password_hash, password_version, password_updated_at
FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) FindUserCredentialByID(ctx context.Context, userID pgtype.UUID) (UserCredential, error) {
	row := q.db.QueryRow(ctx, findUserCredentialByID, userID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.PasswordUpdatedAt,
	)
	return i, err
}
