// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT user_id, full_name, gender, phone_number, avatar_url, date_of_birth, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfileByID(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Gender,
		&i.PhoneNumber,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveUserProfile = `-- name: SaveUserProfile :exec
INSERT INTO user_profiles (
    user_id,
    full_name,
    gender,
    phone_number,
    avatar_url,
    date_of_birth,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveUserProfileParams struct {
	UserID      pgtype.UUID
	FullName    string
	Gender      string
	PhoneNumber pgtype.Text
	AvatarUrl   pgtype.Text
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SaveUserProfile(ctx context.Context, arg SaveUserProfileParams) error {
	_, err := q.db.Exec(ctx, saveUserProfile,
		arg.UserID,
		arg.FullName,
		arg.Gender,
		arg.PhoneNumber,
		arg.AvatarUrl,
		arg.DateOfBirth,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
